### ISSUE TITLE
Having an issue. 

### ISSUE THREAD

**Issue by reddheeraj** [Miriel-py/Archmage#1]
![image](https://user-images.githubusercontent.com/77443480/105577315-cbc78a80-5d9e-11eb-8ae3-826a7e65bebd.png)

This is showing up when I try running it.
what am I missing?

**Comment by MirielCH** [comment]
Oh, you need to create a directory "logs" first. Sorry about that.

**Comment by reddheeraj** [comment]
Okay so once create the directory, it should be working right?
Also, what is the command syntax, etc

**Comment by MirielCH** [comment]
Yes.

The default prefix is - (you can change this)
Use -help to see all the commands.

**Comment by reddheeraj** [comment]
![image](https://user-images.githubusercontent.com/77443480/105577518-2f05ec80-5da0-11eb-8d24-21f947f48d0e.png)

created the logs directory and run the program to see this happen.

**Comment by MirielCH** [comment]
Well, whatever that is, this is not my code. There is no client.py in my bot. And I don't even use .strip() in this project.

**Comment by reddheeraj** [comment]
lmao i downloaded the code from this repository

**Comment by MirielCH** [comment]
Yeah I see the errors are from the discord library.
Looks like you didn't add your token correctly.

**Comment by reddheeraj** [comment]
i created a text document, then added--> DISCORD_TOKEN=token
then saved it with the name .env
am i making a mistake?

**Comment by MirielCH** [comment]
If your file is still a text file, yes. The file needs to be called ".env", no file extension.

**Comment by reddheeraj** [comment]
Hey thanks for your response. The bot is working fine!
